steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'lendex-small'
      - '--zone=us-east1-b'
      - '--command=cd /app && git pull && npm install && pm2 restart all'